name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 0.1.0)'
        required: true
        type: string
      next_version:
        description: 'Next development version (e.g. 0.2.0-SNAPSHOT)'
        required: true
        type: string

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update version to release
        run: |
          sed -i 's/ThisBuild \/ version := ".*"/ThisBuild \/ version := "${{ inputs.version }}"/' build.sbt
          git add build.sbt
          git commit -m "Release ${{ inputs.version }}"

      - name: Create and push tag
        run: |
          git tag v${{ inputs.version }}
          git push origin main
          git push origin v${{ inputs.version }}

      - name: Update to next development version
        run: |
          sed -i 's/ThisBuild \/ version := ".*"/ThisBuild \/ version := "${{ inputs.next_version }}"/' build.sbt
          git add build.sbt
          git commit -m "Bump version to ${{ inputs.next_version }}"
          git push origin main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          name: Release ${{ inputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
